### PR TITLE
Attempted merge of main repo fix for uninitialized data

### PR DESCRIPTION
**Pull request by WestleyArgentum**
NOTE: THIS HAS NOT BEEN FULLY TESTED

There were 6 files with conflicts that I attempted to fix. Unfortunately I cannot compile and test here, I'll be working on that and will update this request if I find anything broken. If someone with access to the repo has a little bit of time I would be really grateful for help testing and producing some binaries.

Most of the conflicts seemed alright, but there are 2 big things to test:
1. A couple functions (win32_SystemFunction036 and randmtzig_create_ziggurat) from rng.jl were moved into librandom.jl. I left them there and applied a change (64 to 32 bit) that was made on the windows fork.
2. There was a change to the function worker_from_id in the file multi.jl from the main repo that I was nervous about. It's probably no big deal, it's just looping over workers and telling them to sleep and yield.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
woah, what's up with this?

**Comment by WestleyArgentum** [comment]
Heh, I apologize, I didn't realize it would spam everyone.

I'm trying to pull in the fix for issue #34 that was committed on the main repo (commit 6111987)

**Comment by vtjnash** [comment]
It spams people who are watching the repository, which is usually a good thing. I think Stefan is just not used to seeing the size of the merge requests that results from keeping the repositories synchronized :). This looks pretty good, but has some random issues during the generation of sys.ji. Also, #34 isn't the only problem preventing making a binary release. (btw, you can also use git cherry-pick to grab specific changes if you want to just test the fixes for #1314 -- I've already tested it locally that way)

**Comment by WestleyArgentum** [comment]
Ah, thanks for the tip. It's cool to think that you could pull more later and not worry because git will just replay the changes. That's a huge advantage over svn.

Anyway, sorry about sys.ji, that was probably my bad... maybe something to do with the changes in the makefile pertaining to sys.ji?

And... I'm just going to be honest and straightforward, we would really like to have a windows build so that we can present our little ide for Julia at a conference in a few days. At this point I'm willing to do anything I can to help you with it. I had some trouble compiling and went back to other work but I'll try again presently.

Would you be willing to post issues for any other problems you know are preventing us from making new binaries?

**Comment by vtjnash** [comment]
I can put up a new binary soon. I'm just waiting for some parts of it to finish rebuilding.

The merge seemed fine. The issues weren't your fault. The issues with sys.ji were (a) just fixed by Jeff (b) because of the removal of jl_core_module, causing an old issue to resurface (not too hard for me to fix once the rebuild has finished)

**Comment by vtjnash** [comment]
@WestleyArgentum can you test this: https://dl.dropbox.com/u/49222256/julia-c8617c4b3a-WINNT-i686.tar.gz and email me to let me know if it works (you should be able to find my address on something I've sent to the mailing list)

**Pull request merged**
